import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/menu/providers";
import { NavbarDemo } from "@/components/menu/NavbarDemo";
import Portfolio from "@/components/footer/footerExpert"; 
import Footerprincipal from "@/components/footer/footer-principal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <NavbarDemo /> 
          {children}
             <Footerprincipal />
          <Portfolio /> 
        </Providers>
      </body>
    </html>
  );
}
